Repository LISTENAI/docs-csk6, pull requests merged in 2022-07, with the labels that each got.

#70 kernel: add system_threads part translate
  .lsopen/sidebar.json
  kernel/system_threads.md
Labels: documentation, ready to merge

#78 modify wificonnect sample
  application/network/files/liza_zep_create.png
  application/network/wifi_connect.md
Labels: documentation, ready to merge

#66 doc: 新增 开发-快速开始
  .lsopen/sidebar.json
  application/getting_start.md
  application/getting_started/installation_linux.md
  application/images/hello_world_flash_finish.png
  application/images/hello_world_output.png
  application/images/lisa_info_zep_sample.png
  application/images/lscloud_add_issue.png
  application/images/lscloud_choose_issue_template.png
Labels: documentation, ready to merge

#67 Feature/lisa command
  .lsopen/sidebar.json
  tool/lisa_plugin_zephyr/basic.md
  tool/lisa_plugin_zephyr/build_flash_debug.md
  tool/lisa_plugin_zephyr/command_detail.md
  tool/lisa_plugin_zephyr/filesystem.md
  tool/lisa_plugin_zephyr/install.md
  tool/lisa_plugin_zephyr/manifest.md
  tool/lisa_plugin_zephyr/release_note.md
  tool/lisa_plugin_zephyr/trouble_shooting.md
Labels: ready to merge

#72 烧录与调试
  .lsopen/sidebar.json
  gdbdebug/csk6_load.md
  gdbdebug/gdbdebug-daplink.md
  gdbdebug/gdbdebug-jlink.md
  gdbdebug/overview.md
Labels: ready to merge

#71 doc: 新增 开发-应用开发
  .lsopen/sidebar.json
  application/application_development.md
  application/env_vars.md
  application/images/lisa_zep_create_dir_sample.png
  application/images/lisa_zep_create_sample.png
  build/dts/howto.md
  build/dts/intro.md
  build/kconfig/extensions.md
  build/kconfig/index.md
  build/kconfig/setting.md
  build/zephyr_cmake_package.md
Labels: documentation, ready to merge

#115 sidebar: 调整侧边栏中不再需要的章节以及错误的标题
  .lsopen/sidebar.json
  kernel/index.md
  service/index.md
Labels: enhancement

#95 Feature/jwzhou kconfig extension
  build/kconfig/Kconfig_extension.md
Labels: ready to merge

#99 doc: 新增 设备树概述
  .lsopen/sidebar.json
  application/application_development.md
  build/dts/api.md
  build/dts/api_usage.md
  build/dts/bindings.md
  build/dts/dt_vs_kconfig.md
  build/dts/howto.md
  build/dts/howtos.md
  build/dts/intro.md
  build/images/zephyr_dt_build_flow.png
  build/images/zephyr_dt_i2c_example.png
  build/images/zephyr_dt_i2c_high_level.png
  build/images/zephyr_dt_inputs_outputs.svg
  build/kconfig/preprocessor_functions.md
Labels: documentation, ready to merge

#107 新增引脚控制
  .lsopen/sidebar.json
  hardware/pinctrl.md
Labels: ready to merge

#93 Feature/jwzhou kconfig custome
  build/kconfig/Kconfig_custom.md
Labels: ready to merge

#90 Feature/jwzhou kconfig tips and demo
  .lsopen/sidebar.json
  build/kconfig/Kconfig_custom.md
  build/kconfig/Kconfig_tips_and_demo.md
  build/kconfig/overview.md
Labels: ready to merge

#123 doc: 新增 设备树 VS Kconfig
  .lsopen/sidebar.json
  build/dts/dt_vs_kconfig.md
Labels: documentation, ready to merge

#124 doc: 新增 设备树疑难解答
  .lsopen/sidebar.json
  build/dts/api_usage.md
  build/dts/howtos.md
  build/dts/troubleshooting.md
Labels: documentation, ready to merge

#103 doc: 新增 设备树设计目标
  .lsopen/sidebar.json
  build/dts/design.md
  build/dts/howtos.md
  build/dts/intro.md
Labels: documentation, ready to merge

#80 doc: 新增 构建系统（ CMake ）
  .lsopen/sidebar.json
  build/cmake/index.md
  build/dts/api.md
  build/dts/index.md
  build/images/build-build-phase-1.svg
  build/images/build-build-phase-2.svg
  build/images/build-build-phase-3.svg
  build/images/build-build-phase-4.svg
  build/images/build-build-phase-5.svg
  build/images/build-build-phase-6.svg
  build/images/build-config-phase.svg
  build/images/build-postprocess-1.svg
  build/images/build-postprocess-2.svg
  build/images/build-postprocess-3.svg
  build/images/build-postprocess-4.svg
  kernel/usermode/index.md
  kernel/usermode/kernelobjects.md
Labels: documentation, ready to merge

#114 doc: 新增 设备树绑定
  .lsopen/sidebar.json
  application/modules.md
  build/dts/api_usage.md
  build/dts/bindings.md
  build/dts/design.md
Labels: documentation, ready to merge

#121 doc: 新增在 C/C++ 中访问设备树
  .lsopen/sidebar.json
  build/dts/api_usage.md
  service/storage/flash_map.md
Labels: documentation, ready to merge

#127 Feature/jwzhou timing
  .lsopen/sidebar.json
  kernel/timing/timers.md
  kernel/timing/timing.md
Labels: ready to merge

#118 Feature/jwzhou shell
  .lsopen/sidebar.json
  service/images/dict_cmd.png
  service/images/dynamic_cmd.png
  service/images/static_cmd.png
  service/images/tab_prompt.png
  service/images/wildcard.png
  service/shell.md
Labels: ready to merge
